// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

class Person implements NanoPackMessage {
  public static TYPE_ID = 1225883824;

  constructor(
    public firstName: string,
    public middleName: string | null,
    public lastName: string,
    public age: number,
    public otherFriend: Person | null,
  ) {}

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Person } | null {
    const reader = new NanoBufReader(bytes);
    return Person.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: Person } | null {
    let ptr = 24;

    const firstNameByteLength = reader.readFieldSize(-1);
    const firstName = reader.readString(ptr, firstNameByteLength);
    ptr += firstNameByteLength;

    let middleName: string | null;
    if (reader.readFieldSize(0) >= 0) {
      const middleNameByteLength = reader.readFieldSize(0);
      middleName = reader.readString(ptr, middleNameByteLength);
      ptr += middleNameByteLength;
    } else {
      middleName = null;
    }

    const lastNameByteLength = reader.readFieldSize(1);
    const lastName = reader.readString(ptr, lastNameByteLength);
    ptr += lastNameByteLength;

    const age = reader.readInt8(ptr);
    ptr += 1;

    let otherFriend: Person | null;
    if (reader.readFieldSize(3) >= 0) {
      const maybeOtherFriend = Person.fromReader(reader.newReaderAt(ptr));
      if (!maybeOtherFriend) {
        return null;
      }
      otherFriend = maybeOtherFriend.result;
      ptr += maybeOtherFriend.bytesRead;
    } else {
      otherFriend = null;
    }

    return {
      bytesRead: ptr,
      result: new Person(firstName, middleName, lastName, age, otherFriend),
    };
  }

  public get typeId(): number {
    return 1225883824;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(24);
    writer.writeTypeId(1225883824);

    const firstNameByteLength = writer.appendString(this.firstName);
    writer.writeFieldSize(-1, firstNameByteLength);

    if (this.middleName) {
      const middleNameByteLength = writer.appendString(this.middleName);
      writer.writeFieldSize(0, middleNameByteLength);
    } else {
      writer.writeFieldSize(0, -1);
    }

    const lastNameByteLength = writer.appendString(this.lastName);
    writer.writeFieldSize(1, lastNameByteLength);

    writer.appendInt8(this.age);
    writer.writeFieldSize(2, 1);

    if (this.otherFriend) {
      const otherFriendData = this.otherFriend.bytes();
      writer.appendBytes(otherFriendData);
      writer.writeFieldSize(3, otherFriendData.byteLength);
    } else {
      writer.writeFieldSize(3, -1);
    }

    return writer.bytes;
  }

  public bytesWithLengthPrefix(): Uint8Array {
    const writer = new NanoBufWriter(24 + 4, true);
    writer.writeTypeId(1225883824);

    const firstNameByteLength = writer.appendString(this.firstName);
    writer.writeFieldSize(-1, firstNameByteLength);

    if (this.middleName) {
      const middleNameByteLength = writer.appendString(this.middleName);
      writer.writeFieldSize(0, middleNameByteLength);
    } else {
      writer.writeFieldSize(0, -1);
    }

    const lastNameByteLength = writer.appendString(this.lastName);
    writer.writeFieldSize(1, lastNameByteLength);

    writer.appendInt8(this.age);
    writer.writeFieldSize(2, 1);

    if (this.otherFriend) {
      const otherFriendData = this.otherFriend.bytes();
      writer.appendBytes(otherFriendData);
      writer.writeFieldSize(3, otherFriendData.byteLength);
    } else {
      writer.writeFieldSize(3, -1);
    }

    writer.writeLengthPrefix(writer.currentSize - 4);

    return writer.bytes;
  }
}

export { Person };
