package cxxgenerator

type messageHeaderFileTemplateInfo struct {
	MessageName            string
	ParentMessageName      string
	TypeID                 int
	IncludeGuardName       string
	StdImports             []string
	ParentSchemaImportPath string

	FieldDeclarationLines []string
}

const MessageHeaderFile = `// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef {{.IncludeGuardName}}
#define {{.IncludeGuardName}}

#include <vector>
{{range .StdImports}}
#include <{{.}}>
{{end}}
{{if .ParentSchemaImportPath -}}
#include <{{.ParentSchemaImportPath}}>
{{- else -}}
#include <nanopack/message.hxx>
{{-end}}
#include <nanopack/reader.hxx>

struct {{.MessageName}} : {{if .ParentSchemaImportPath}}{{.ParentMessageName}}{{else}}NanoPack::Message{{end}} {
  static constexpr int32_t TYPE_ID = {{.TypeID}};
  {{range .FieldDeclarationLines}}
  {{.}}
  {{end}}
  
  
}

#endif
`
