// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let ClickEvent_typeID: TypeID = 2

class ClickEvent: NanoPackMessage {
  var typeID: TypeID { return 2 }

  let x: Double
  let y: Double
  let timestamp: Int64

  init(x: Double, y: Double, timestamp: Int64) {
    self.x = x
    self.y = y
    self.timestamp = timestamp
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 16

    let x: Double = data.read(at: ptr)
    ptr += 8

    let y: Double = data.read(at: ptr)
    ptr += 8

    let timestamp: Int64 = data.read(at: ptr)
    ptr += 8

    self.x = x
    self.y = y
    self.timestamp = timestamp
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 16

    let x: Double = data.read(at: ptr)
    ptr += 8

    let y: Double = data.read(at: ptr)
    ptr += 8

    let timestamp: Int64 = data.read(at: ptr)
    ptr += 8

    self.x = x
    self.y = y
    self.timestamp = timestamp

    bytesRead = ptr - data.startIndex
  }

  func data() -> Data? {
    let offset = 0

    var data = Data()
    data.reserveCapacity(16)

    data.append(int: Int32(ClickEvent_typeID))
    data.append([0], count: 3 * 4)

    data.write(size: 8, ofField: 0, offset: offset)
    data.append(double: x)

    data.write(size: 8, ofField: 1, offset: offset)
    data.append(double: y)

    data.write(size: 8, ofField: 2, offset: offset)
    data.append(int: timestamp)

    return data
  }

  func dataWithLengthPrefix() -> Data? {
    let offset = 4

    var data = Data()
    data.reserveCapacity(16 + 4)

    data.append(int: Int32(0))
    data.append(int: Int32(ClickEvent_typeID))
    data.append([0], count: 3 * 4)

    data.write(size: 8, ofField: 0, offset: offset)
    data.append(double: x)

    data.write(size: 8, ofField: 1, offset: offset)
    data.append(double: y)

    data.write(size: 8, ofField: 2, offset: offset)
    data.append(int: timestamp)

    data.write(size: data.count, at: 0)

    return data
  }
}
