// AUTOMATICALLY GENERATED BY NANOC

#ifndef NESTED_MESSAGE_NP_HXX
#define NESTED_MESSAGE_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <string>

struct NestedMessage : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 2309634176;

  std::string string_field;

  NestedMessage() = default;

  explicit NestedMessage(std::string string_field);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

#endif
