// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "person.np.hxx"

Person::Person(std::string first_name, std::optional<std::string> middle_name,
               std::string last_name, int8_t age,
               std::shared_ptr<Person> other_friend)
    : first_name(std::move(first_name)), middle_name(std::move(middle_name)),
      last_name(std::move(last_name)), age(age),
      other_friend(std::move(other_friend)) {}

Person::Person(const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 24;

  const int32_t first_name_size = reader.read_field_size(0);
  first_name = reader.read_string(ptr, first_name_size);
  ptr += first_name_size;

  if (reader.read_field_size(1) < 0) {
    this->middle_name = std::nullopt;
  } else {
    const int32_t middle_name_size = reader.read_field_size(1);
    middle_name = reader.read_string(ptr, middle_name_size);
    ptr += middle_name_size;
  }

  const int32_t last_name_size = reader.read_field_size(2);
  last_name = reader.read_string(ptr, last_name_size);
  ptr += last_name_size;

  const int8_t age = reader.read_int8(ptr);
  ptr += 1;
  this->age = age;

  if (reader.read_field_size(4) < 0) {
    other_friend = nullptr;
  } else {
    int other_friend_bytes_read = 0;
    other_friend =
        std::make_shared<Person>(begin + ptr, other_friend_bytes_read);
    ptr += other_friend_bytes_read;
  }

  bytes_read = ptr;
}

Person::Person(std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : Person(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Person::type_id() const { return TYPE_ID; }

std::vector<uint8_t> Person::data() const {
  std::vector<uint8_t> buf(24);
  NanoPack::Writer writer(&buf);

  writer.write_type_id(TYPE_ID);

  writer.write_field_size(0, first_name.size());
  writer.append_string(first_name);

  if (middle_name.has_value()) {
    const auto middle_name = this->middle_name.value();
    writer.write_field_size(1, middle_name.size());
    writer.append_string(middle_name);
  } else {
    writer.write_field_size(1, -1);
  }

  writer.write_field_size(2, last_name.size());
  writer.append_string(last_name);

  writer.write_field_size(3, 1);
  writer.append_int8(age);

  if (other_friend != nullptr) {
    const std::vector<uint8_t> other_friend_data = other_friend->data();
    writer.append_bytes(other_friend_data);
    writer.write_field_size(4, other_friend_data.size());
  } else {
    writer.write_field_size(4, -1);
  }

  return buf;
}

std::vector<uint8_t> Person::data_with_length_prefix() const {
  std::vector<uint8_t> buf(24 + 4);
  NanoPack::Writer writer(&buf, 4);

  writer.write_type_id(TYPE_ID);

  writer.write_field_size(0, first_name.size());
  writer.append_string(first_name);

  if (middle_name.has_value()) {
    const auto middle_name = this->middle_name.value();
    writer.write_field_size(1, middle_name.size());
    writer.append_string(middle_name);
  } else {
    writer.write_field_size(1, -1);
  }

  writer.write_field_size(2, last_name.size());
  writer.append_string(last_name);

  writer.write_field_size(3, 1);
  writer.append_int8(age);

  if (other_friend != nullptr) {
    const std::vector<uint8_t> other_friend_data = other_friend->data();
    writer.append_bytes(other_friend_data);
    writer.write_field_size(4, other_friend_data.size());
  } else {
    writer.write_field_size(4, -1);
  }

  const size_t byte_size = buf.size() - 4;
  buf[0] = byte_size & 0xFF;
  buf[1] = byte_size & 0xFF00;
  buf[2] = byte_size & 0xFF0000;
  buf[3] = byte_size & 0xFF000000;

  return buf;
}
