// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import type { NanoPackMessage } from "nanopack";

import { Text } from "./text.np.js";
import { Widget } from "./widget.np.js";

function makeNanoPackMessage(
  bytes: Uint8Array,
  typeId: number,
): { bytesRead: number; result: NanoPackMessage } | null {
  switch (typeId) {
    case 2:
      return Text.fromBytes(bytes);
    case 1:
      return Widget.fromBytes(bytes);
    default:
      return null;
  }
}

export { makeNanoPackMessage };
