// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

class ClickEvent implements NanoPackMessage {
  public static TYPE_ID = 2;

  constructor(
    public x: number,
    public y: number,
    public timestamp: bigint,
  ) {}

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: ClickEvent } | null {
    const reader = new NanoBufReader(bytes);
    return ClickEvent.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: ClickEvent } | null {
    let ptr = 16;

    const x = reader.readDouble(ptr);
    ptr += 8;

    const y = reader.readDouble(ptr);
    ptr += 8;

    const timestamp = reader.readInt64(ptr);
    ptr += 8;

    return { bytesRead: ptr, result: new ClickEvent(x, y, timestamp) };
  }

  public get typeId(): number {
    return 2;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(16);
    writer.writeTypeId(2);

    writer.appendDouble(this.x);
    writer.writeFieldSize(0, 8);

    writer.appendDouble(this.y);
    writer.writeFieldSize(1, 8);

    writer.appendInt64(this.timestamp);
    writer.writeFieldSize(2, 8);

    return writer.bytes;
  }

  public bytesWithLengthPrefix(): Uint8Array {
    const writer = new NanoBufWriter(16 + 4, true);
    writer.writeTypeId(2);

    writer.appendDouble(this.x);
    writer.writeFieldSize(0, 8);

    writer.appendDouble(this.y);
    writer.writeFieldSize(1, 8);

    writer.appendInt64(this.timestamp);
    writer.writeFieldSize(2, 8);

    writer.writeLengthPrefix(writer.currentSize - 4);

    return writer.bytes;
  }
}

export { ClickEvent };
