// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

const Alignment = {
  START: "start",
  END: "end",
  CENTER: "center",
  TOP: "top",
  BOTTOM: "bottom",
} as const;

type TAlignment = (typeof Alignment)[keyof typeof Alignment];

export { Alignment };
export type { TAlignment };
