// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

const Week = {
  SUNDAY: 0,
  MONDAY: 1,
  TUESDAY: 2,
  WEDNESDAY: 3,
  THURSDAY: 4,
  FRIDAY: 5,
  SATURDAY: 6,
} as const;

type TWeek = (typeof Week)[keyof typeof Week];

export { Week };
export type { TWeek };
