// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "make_widget.np.hxx"

#include "text.np.hxx"

std::unique_ptr<Widget> make_widget(NanoPack::Reader &reader,
                                    size_t &bytes_read) {
  switch (reader.read_type_id()) {
  case 1676374721: {
    auto ptr = std::make_unique<Widget>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  case 3495336243: {
    auto ptr = std::make_unique<Text>();
    bytes_read = ptr->read_from(reader);
    return ptr;
  }
  default:
    return nullptr;
  }
}
