// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef WIDGET_FACTORY_NP_HXX
#define WIDGET_FACTORY_NP_HXX

#include "widget.np.hxx"
#include <memory>
#include <nanopack/reader.hxx>

std::unique_ptr<Widget> make_widget(NanoPack::Reader &reader,
                                    size_t &bytes_read);

#endif
