// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include "nanopack_message_factory.np.hxx"

#include "text.np.hxx"
#include "widget.np.hxx"

std::unique_ptr<NanoPack::Message>
make_nanopack_message(std::vector<uint8_t>::const_iterator data_iter,
                      int &bytes_read) {
  switch (const NanoPack::Reader reader(data_iter); reader.read_type_id()) {
  case 1:
    return std::make_unique<Widget>(reader, bytes_read);
  case 2:
    return std::make_unique<Text>(reader, bytes_read);
  default:
    return nullptr;
  }
}
