// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "text.np.hxx"

Text::Text(int32_t id, std::string content)
    : Widget(id), content(std::move(content)) {}

Text::Text(const NanoPack::Reader &reader, int &bytes_read) : Widget() {
  const auto begin = reader.begin();
  int ptr = 12;

  const int32_t id = reader.read_int32(ptr);
  ptr += 4;
  this->id = id;

  const int32_t content_size = reader.read_field_size(1);
  content = reader.read_string(ptr, content_size);
  ptr += content_size;

  bytes_read = ptr;
}

Text::Text(std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : Text(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Text::type_id() const { return TYPE_ID; }

std::vector<uint8_t> Text::data() const {
  std::vector<uint8_t> buf(12);
  NanoPack::Writer writer(&buf);

  writer.write_type_id(TYPE_ID);

  writer.write_field_size(0, 4);
  writer.append_int32(id);

  writer.write_field_size(1, content.size());
  writer.append_string(content);

  return buf;
}

std::vector<uint8_t> Text::data_with_length_prefix() const {
  std::vector<uint8_t> buf(12 + 4);
  NanoPack::Writer writer(&buf, 4);

  writer.write_type_id(TYPE_ID);

  writer.write_field_size(0, 4);
  writer.append_int32(id);

  writer.write_field_size(1, content.size());
  writer.append_string(content);

  const size_t byte_size = buf.size() - 4;
  buf[0] = byte_size & 0xFF;
  buf[1] = byte_size & 0xFF00;
  buf[2] = byte_size & 0xFF0000;
  buf[3] = byte_size & 0xFF000000;

  return buf;
}
