// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "invoke_callback.np.hxx"

InvokeCallback::InvokeCallback(int32_t handle, NanoPack::Any args)
    : handle(handle), args(std::move(args)) {}

InvokeCallback::InvokeCallback(const NanoPack::Reader &reader,
                               int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 12;

  const int32_t handle = reader.read_int32(ptr);
  ptr += 4;
  this->handle = handle;

  const int32_t args_byte_size = reader.read_field_size(1);
  args = NanoPack::Any(begin + ptr, begin + ptr + args_byte_size);
  ptr += args_byte_size;

  bytes_read = ptr;
}

InvokeCallback::InvokeCallback(std::vector<uint8_t>::const_iterator begin,
                               int &bytes_read)
    : InvokeCallback(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId InvokeCallback::type_id() const { return TYPE_ID; }

int InvokeCallback::header_size() const { return 12; }

size_t InvokeCallback::write_to(std::vector<uint8_t> &buf, int offset) const {
  const size_t buf_size_before = buf.size();

  buf.resize(offset + 12);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, 4, offset, buf);
  NanoPack::append_int32(handle, buf);

  NanoPack::write_field_size(1, args.size(), offset, buf);
  NanoPack::append_bytes(args.data(), buf);

  return buf.size() - buf_size_before;
}

std::vector<uint8_t> InvokeCallback::data() const {
  std::vector<uint8_t> buf(12);
  write_to(buf, 0);
  return buf;
}
