// AUTOMATICALLY GENERATED BY NANOC

#ifndef INVOKE_CALLBACK_NP_HXX
#define INVOKE_CALLBACK_NP_HXX
#include <nanopack/any.hxx>
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

struct InvokeCallback : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 2013877267;

  int32_t handle;
  NanoPack::Any args;

  InvokeCallback() = default;

  InvokeCallback(int32_t handle, NanoPack::Any args);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

#endif
