// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let Text_typeID: TypeID = 2

class Text: Widget {
  override var typeID: TypeID { return 2 }

  let content: String

  init(id: Int32, content: String) {
    self.content = content
    super.init(id: id)
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 12

    let id: Int32 = data.read(at: ptr)
    ptr += 4

    let contentSize = data.readSize(ofField: 1)
    guard let content = data.read(at: ptr, withLength: contentSize) else {
      return nil
    }
    ptr += contentSize

    self.content = content
    super.init(id: id)
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 12

    let id: Int32 = data.read(at: ptr)
    ptr += 4

    let contentSize = data.readSize(ofField: 1)
    guard let content = data.read(at: ptr, withLength: contentSize) else {
      return nil
    }
    ptr += contentSize

    self.content = content
    super.init(id: id)

    bytesRead = ptr - data.startIndex
  }

  override func data() -> Data? {
    let offset = 0

    var data = Data()
    data.reserveCapacity(12)

    data.append(int: Int32(Text_typeID))
    data.append([0], count: 2 * 4)

    data.write(size: 4, ofField: 0, offset: offset)
    data.append(int: id)

    data.write(size: content.lengthOfBytes(using: .utf8), ofField: 1, offset: offset)
    data.append(string: content)

    return data
  }

  override func dataWithLengthPrefix() -> Data? {
    let offset = 4

    var data = Data()
    data.reserveCapacity(12 + 4)

    data.append(int: Int32(0))
    data.append(int: Int32(Text_typeID))
    data.append([0], count: 2 * 4)

    data.write(size: 4, ofField: 0, offset: offset)
    data.append(int: id)

    data.write(size: content.lengthOfBytes(using: .utf8), ofField: 1, offset: offset)
    data.append(string: content)

    data.write(size: data.count, at: 0)

    return data
  }
}
