// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "column.np.hxx"

Column::Column(const Alignment &alignment) : alignment(alignment) {}

Column::Column(const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 8;

  const int32_t alignment_size = reader.read_field_size(0);
  const std::string alignment_raw_value =
      reader.read_string(ptr, alignment_size);
  ptr += alignment_size;
  alignment = Alignment(alignment_raw_value);

  bytes_read = ptr;
}

Column::Column(std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : Column(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId Column::type_id() const { return TYPE_ID; }

int Column::header_size() const { return 8; }

size_t Column::write_to(std::vector<uint8_t> &buf, int offset) const {
  const size_t buf_size_before = buf.size();

  buf.resize(offset + 8);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, alignment.value().size(), offset, buf);
  NanoPack::append_string(alignment.value(), buf);

  return buf.size() - buf_size_before;
}

std::vector<uint8_t> Column::data() const {
  std::vector<uint8_t> buf(8);
  write_to(buf, 0);
  return buf;
}
