// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef COLUMN_NP_HXX
#define COLUMN_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "alignment.np.hxx"

struct Column : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 2;

  Alignment alignment;

  Column() = default;

  explicit Column(const Alignment &alignment);

  Column(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  Column(const NanoPack::Reader &reader, int &bytes_read);

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;

  [[nodiscard]] std::vector<uint8_t> data_with_length_prefix() const override;
};

#endif
