// AUTOMATICALLY GENERATED BY NANOC

#ifndef COLUMN_NP_HXX
#define COLUMN_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

#include "alignment.np.hxx"

struct Column : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 2415007766;

  Alignment alignment;

  Column() = default;

  explicit Column(const Alignment &alignment);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

#endif
