// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#ifndef NP_DATE_NP_HXX
#define NP_DATE_NP_HXX

#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>
#include <vector>

#include "month.np.hxx"
#include "week.np.hxx"

struct NpDate : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1732634645;

  int8_t day;
  Week week;
  Month month;
  int32_t year;

  NpDate() = default;

  NpDate(int8_t day, const Week &week, const Month &month, int32_t year);

  NpDate(std::vector<uint8_t>::const_iterator begin, int &bytes_read);

  NpDate(const NanoPack::Reader &reader, int &bytes_read);

  size_t write_to(std::vector<uint8_t> &buf, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] int header_size() const override;

  [[nodiscard]] std::vector<uint8_t> data() const override;
};

#endif
