// AUTOMATICALLY GENERATED BY NANOC

#ifndef NP_DATE_NP_HXX
#define NP_DATE_NP_HXX
#include <nanopack/message.hxx>
#include <nanopack/nanopack.hxx>
#include <nanopack/reader.hxx>

#include "month.np.hxx"
#include "week.np.hxx"

struct NpDate : NanoPack::Message {
  static constexpr NanoPack::TypeId TYPE_ID = 1732634645;

  int8_t day;
  Week week;
  Month month;
  int32_t year;

  NpDate() = default;

  NpDate(int8_t day, const Week &week, const Month &month, int32_t year);

  size_t read_from(NanoPack::Reader &reader);

  size_t write_to(NanoPack::Writer &writer, int offset) const override;

  [[nodiscard]] NanoPack::TypeId type_id() const override;

  [[nodiscard]] size_t header_size() const override;
};

#endif
