// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

#include <nanopack/reader.hxx>
#include <nanopack/writer.hxx>

#include "np_date.np.hxx"

NpDate::NpDate(int8_t day, const Week &week, const Month &month, int32_t year)
    : day(day), week(week), month(month), year(year) {}

NpDate::NpDate(const NanoPack::Reader &reader, int &bytes_read) {
  const auto begin = reader.begin();
  int ptr = 20;

  const int8_t day = reader.read_int8(ptr);
  ptr += 1;
  this->day = day;

  const int8_t week_raw_value = reader.read_int8(ptr);
  ptr += 1;
  week = Week(week_raw_value);

  const int8_t month_raw_value = reader.read_int8(ptr);
  ptr += 1;
  month = Month(month_raw_value);

  const int32_t year = reader.read_int32(ptr);
  ptr += 4;
  this->year = year;

  bytes_read = ptr;
}

NpDate::NpDate(std::vector<uint8_t>::const_iterator begin, int &bytes_read)
    : NpDate(NanoPack::Reader(begin), bytes_read) {}

NanoPack::TypeId NpDate::type_id() const { return TYPE_ID; }

int NpDate::header_size() const { return 20; }

size_t NpDate::write_to(std::vector<uint8_t> &buf, int offset) const {
  const size_t buf_size_before = buf.size();

  buf.resize(offset + 20);

  NanoPack::write_type_id(TYPE_ID, offset, buf);

  NanoPack::write_field_size(0, 1, offset, buf);
  NanoPack::append_int8(day, buf);

  NanoPack::write_field_size(1, 1, offset, buf);
  NanoPack::append_int8(week.value(), buf);

  NanoPack::write_field_size(2, 1, offset, buf);
  NanoPack::append_int8(month.value(), buf);

  NanoPack::write_field_size(3, 4, offset, buf);
  NanoPack::append_int32(year, buf);

  return buf.size() - buf_size_before;
}

std::vector<uint8_t> NpDate::data() const {
  std::vector<uint8_t> buf(20);
  write_to(buf, 0);
  return buf;
}
