// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation

enum Alignment: String {
  case start = "start"
  case end = "end"
  case center = "center"
  case top = "top"
  case bottom = "bottom"
}
