// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation
import NanoPack

let Column_typeID: TypeID = 2_415_007_766

class Column: NanoPackMessage {
  var typeID: TypeID { return 2_415_007_766 }

  var headerSize: Int { return 8 }

  let alignment: Alignment

  init(alignment: Alignment) {
    self.alignment = alignment
  }

  required init?(data: Data) {
    var ptr = data.startIndex + 8

    let alignmentSize = data.readSize(ofField: 0)
    guard let alignmentRawValue = data.read(at: ptr, withLength: alignmentSize) else {
      return nil
    }
    ptr += alignmentSize
    guard let alignment = Alignment(rawValue: alignmentRawValue) else {
      return nil
    }

    self.alignment = alignment
  }

  required init?(data: Data, bytesRead: inout Int) {
    var ptr = data.startIndex + 8

    let alignmentSize = data.readSize(ofField: 0)
    guard let alignmentRawValue = data.read(at: ptr, withLength: alignmentSize) else {
      return nil
    }
    ptr += alignmentSize
    guard let alignment = Alignment(rawValue: alignmentRawValue) else {
      return nil
    }

    self.alignment = alignment

    bytesRead = ptr - data.startIndex
  }

  func write(to data: inout Data, offset: Int) -> Int {
    let dataCountBefore = data.count

    data.reserveCapacity(offset + 8)

    data.append(typeID: TypeID(Column_typeID))
    data.append([0], count: 1 * 4)

    data.write(size: alignment.rawValue.lengthOfBytes(using: .utf8), ofField: 0, offset: offset)
    data.append(string: alignment.rawValue)

    return data.count - dataCountBefore
  }

  func data() -> Data? {
    var data = Data()
    _ = write(to: &data, offset: 0)
    return data
  }
}
