// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import Foundation

enum Month: Int8 {
  case november = 11
  case january = 1
  case february = 2
  case march = 3
  case july = 7
  case october = 10
  case december = 12
  case april = 4
  case may = 5
  case june = 6
  case august = 8
  case september = 9
}
